import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
django.setup()

from django.contrib.auth import get_user_model
from products.models import Product

User = get_user_model()

# Ensure seller Moqeed exists
seller, created = User.objects.get_or_create(
    username='Moqeed',
    defaults={'email': 'moqeed@maazacafe.com', 'user_type': 'seller'}
)
seller.set_password('Moqeed@123')
seller.user_type = 'seller'
seller.save()

# Clear existing non-restaurant products
Product.objects.all().delete()

dishes = [
    # ------------------ TIFFINS ------------------
    {
        'title': 'Crispy Butter Masala Dosa',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 85.00,
        'imageUrl': 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': True,
        'description': 'Golden brown crispy crepe roasted with pure butter, stuffed with spiced potato masala and served with coconut chutney & piping hot sambar.',
        'availability': 'In Stock',
        'total_reviews': 342,
    },
    {
        'title': 'Golden Ghee Roast Plain Dosa',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 70.00,
        'imageUrl': 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Crispy, paper-thin golden crepe made with fermented rice and lentil batter, smeared with pure cow ghee.',
        'availability': 'In Stock',
        'total_reviews': 210,
    },
    {
        'title': 'Ghee Podi Idli (3 Pcs)',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 70.00,
        'imageUrl': 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Steamed fluffy rice cakes generously tossed in aromatic spiced lentil powder (karampodi) and organic desi ghee.',
        'availability': 'In Stock',
        'total_reviews': 188,
    },
    {
        'title': 'Medu Vada Sambar (2 Pcs)',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 65.00,
        'imageUrl': 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
        'rating': 4.5,
        'is_prime': False,
        'description': 'Crispy golden fried lentil donuts with a crunchy crust and fluffy interior, dipped in aromatic vegetable sambar.',
        'availability': 'In Stock',
        'total_reviews': 215,
    },
    {
        'title': 'Hot Puri Bhaji (3 Pcs)',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 80.00,
        'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
        'rating': 4.4,
        'is_prime': False,
        'description': 'Puffed whole wheat fried flatbreads served with mildly spiced turmeric potato masala and tangy pickle.',
        'availability': 'In Stock',
        'total_reviews': 160,
    },
    {
        'title': 'Ghee Rava Upma with Chutney',
        'brand': 'Maaza Tiffins',
        'category': 'Tiffins',
        'price': 60.00,
        'imageUrl': 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
        'rating': 4.3,
        'is_prime': False,
        'description': 'Slow-roasted semolina tempered with mustard seeds, curry leaves, ginger, cashews, and fresh coconut chutney.',
        'availability': 'In Stock',
        'total_reviews': 95,
    },

    # ------------------ CHINESE / FASTFOOD ------------------
    {
        'title': 'Veg Hakka Noodles',
        'brand': 'Maaza Wok',
        'category': 'Chinese / Fastfood',
        'price': 140.00,
        'imageUrl': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
        'rating': 4.5,
        'is_prime': False,
        'description': 'Wok-tossed noodles with shredded cabbage, carrots, bell peppers, scallions, and signature Indo-Chinese spices.',
        'availability': 'In Stock',
        'total_reviews': 230,
    },
    {
        'title': 'Chicken Schezwan Fried Rice',
        'brand': 'Maaza Wok',
        'category': 'Chinese / Fastfood',
        'price': 190.00,
        'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': True,
        'description': 'Long-grain basmati rice stir-fried with juicy chicken chunks, scrambled egg, and fiery homemade Schezwan sauce.',
        'availability': 'In Stock',
        'total_reviews': 310,
    },
    {
        'title': 'Crispy Veg Manchurian Gravy',
        'brand': 'Maaza Wok',
        'category': 'Chinese / Fastfood',
        'price': 150.00,
        'imageUrl': 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
        'rating': 4.4,
        'is_prime': False,
        'description': 'Golden vegetable dumplings simmered in a savory, tangy garlic-soy sauce with fresh spring onions.',
        'availability': 'In Stock',
        'total_reviews': 175,
    },
    {
        'title': 'Fiery Chilli Chicken Dry',
        'brand': 'Maaza Wok',
        'category': 'Chinese / Fastfood',
        'price': 210.00,
        'imageUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Tender fried chicken bites tossed with fresh green chillies, diced onions, bell peppers, and dark soy glaze.',
        'availability': 'In Stock',
        'total_reviews': 285,
    },
    {
        'title': 'Crispy Fried Chilli Baby Corn',
        'brand': 'Maaza Wok',
        'category': 'Chinese / Fastfood',
        'price': 160.00,
        'imageUrl': 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80',
        'rating': 4.3,
        'is_prime': False,
        'description': 'Crunchy battered baby corn fried to perfection and tossed in spicy pepper-garlic glaze.',
        'availability': 'In Stock',
        'total_reviews': 120,
    },

    # ------------------ BIRYANI ------------------
    {
        'title': 'Hyderabadi Chicken Dum Biryani',
        'brand': 'Maaza Royal Kitchen',
        'category': 'Biryani',
        'price': 260.00,
        'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'World-famous authentic Hyderabadi dum biryani prepared with marinated chicken, saffron-infused basmati rice, fried onions, and royal spices, served with Mirchi Ka Salan and Raita.',
        'availability': 'In Stock',
        'total_reviews': 540,
    },
    {
        'title': 'Special Mutton Dum Biryani',
        'brand': 'Maaza Royal Kitchen',
        'category': 'Biryani',
        'price': 340.00,
        'imageUrl': 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'Slow-cooked succulent tender goat meat layered with fragrant long-grain rice, aromatic ghee, and hand-ground spices in sealed handi.',
        'availability': 'In Stock',
        'total_reviews': 420,
    },
    {
        'title': 'Royal Veg Dum Biryani',
        'brand': 'Maaza Royal Kitchen',
        'category': 'Biryani',
        'price': 200.00,
        'imageUrl': 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Garden-fresh vegetables, paneer cubes, and mint leaves cooked in dum style with saffron basmati rice.',
        'availability': 'In Stock',
        'total_reviews': 195,
    },
    {
        'title': 'Double Egg Dum Biryani',
        'brand': 'Maaza Royal Kitchen',
        'category': 'Biryani',
        'price': 190.00,
        'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
        'rating': 4.5,
        'is_prime': False,
        'description': 'Roasted spiced boiled eggs embedded in deeply aromatic dum biryani rice, served with creamy raita.',
        'availability': 'In Stock',
        'total_reviews': 165,
    },

    # ------------------ MEALS ------------------
    {
        'title': 'Traditional South Indian Thali',
        'brand': 'Maaza Kitchen',
        'category': 'Meals',
        'price': 180.00,
        'imageUrl': 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Wholesome feast with steamed rice, sambar, rasam, kootu, veg poriyal, curd, crispy papad, sweet payasam, and homemade pickle.',
        'availability': 'In Stock',
        'total_reviews': 240,
    },
    {
        'title': 'Deluxe North Indian Executive Thali',
        'brand': 'Maaza Kitchen',
        'category': 'Meals',
        'price': 220.00,
        'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': True,
        'description': 'Paneer butter masala, dal makhani, seasonal sabzi, jeera rice, 2 butter rotis, raita, gulab jamun, and salad.',
        'availability': 'In Stock',
        'total_reviews': 290,
    },
    {
        'title': 'Creamy Curd Rice with Tadka',
        'brand': 'Maaza Kitchen',
        'category': 'Meals',
        'price': 100.00,
        'imageUrl': 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&auto=format&fit=crop&q=80',
        'rating': 4.5,
        'is_prime': False,
        'description': 'Refreshing comfort bowl of soft rice whipped with fresh curd, tempered with mustard seeds, curry leaves, green chillies, and pomegranate pearls.',
        'availability': 'In Stock',
        'total_reviews': 130,
    },
    {
        'title': 'Ghee Sambar Rice Special Bowl',
        'brand': 'Maaza Kitchen',
        'category': 'Meals',
        'price': 110.00,
        'imageUrl': 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Hot homestyle lentil sambar simmered with veggies and blended with rice, topped with a ladle of pure golden ghee.',
        'availability': 'In Stock',
        'total_reviews': 140,
    },

    # ------------------ IRANI TEA ------------------
    {
        'title': 'Special Irani Dum Chai',
        'brand': 'Maaza Cafe Chai Khana',
        'category': 'Irani Tea',
        'price': 30.00,
        'imageUrl': 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'The signature Hyderabadi Irani Chai! Thick, creamy condensed milk infused with slow-brewed decoction for the ultimate soul-warming sip.',
        'availability': 'In Stock',
        'total_reviews': 620,
    },
    {
        'title': 'Irani Chai with Osmania Biscuits (4 Pcs)',
        'brand': 'Maaza Cafe Chai Khana',
        'category': 'Irani Tea',
        'price': 55.00,
        'imageUrl': 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'Pairing made in heaven: our rich Irani Dum Chai served alongside fresh melt-in-mouth buttery Osmania biscuits.',
        'availability': 'In Stock',
        'total_reviews': 480,
    },
    {
        'title': 'Royal Zafrani Malai Chai',
        'brand': 'Maaza Cafe Chai Khana',
        'category': 'Irani Tea',
        'price': 45.00,
        'imageUrl': 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Kashmiri saffron strands simmered into velvety cream milk tea, garnished with crushed green cardamom and pistachio.',
        'availability': 'In Stock',
        'total_reviews': 295,
    },
    {
        'title': 'Toasted Bun Maska with Chai',
        'brand': 'Maaza Cafe Chai Khana',
        'category': 'Irani Tea',
        'price': 70.00,
        'imageUrl': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Freshly baked soft bun generously smothered with salted Amul butter and fruit jam, served with hot Irani tea for dipping.',
        'availability': 'In Stock',
        'total_reviews': 310,
    },

    # ------------------ SHAWARMA ------------------
    {
        'title': 'Classic Chicken Shawarma Roll',
        'brand': 'Maaza Grill',
        'category': 'Shawarma',
        'price': 130.00,
        'imageUrl': 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': True,
        'description': 'Marinated chicken carved from vertical rotisserie grill, wrapped in soft pita bread with garlic toum, pickles, and fries.',
        'availability': 'In Stock',
        'total_reviews': 390,
    },
    {
        'title': 'Special Rumali Chicken Shawarma',
        'brand': 'Maaza Grill',
        'category': 'Shawarma',
        'price': 160.00,
        'imageUrl': 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Generous loaded chicken filling rolled inside paper-thin hand-stretched Rumali roti with secret house spice blend.',
        'availability': 'In Stock',
        'total_reviews': 280,
    },
    {
        'title': 'Jumbo Cheese Chicken Shawarma',
        'brand': 'Maaza Grill',
        'category': 'Shawarma',
        'price': 190.00,
        'imageUrl': 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Extra portion of juicy grilled chicken topped with melted mozzarella, cheddar sauce, jalapeños, and creamy garlic mayonnaise.',
        'availability': 'In Stock',
        'total_reviews': 210,
    },
    {
        'title': 'Crispy Falafel Shawarma Roll',
        'brand': 'Maaza Grill',
        'category': 'Shawarma',
        'price': 120.00,
        'imageUrl': 'https://images.unsplash.com/photo-1593504049359-74330189a345?w=600&auto=format&fit=crop&q=80',
        'rating': 4.4,
        'is_prime': False,
        'description': 'Crispy spiced chickpea patties, fresh parsley, tomatoes, pickled turnips, and creamy sesame tahini sauce in toasted pita.',
        'availability': 'In Stock',
        'total_reviews': 145,
    },

    # ------------------ CHAT BANDI ------------------
    {
        'title': 'Hyderabadi Pani Puri (8 Pcs)',
        'brand': 'Maaza Chat Bandi',
        'category': 'Chat Bandi',
        'price': 50.00,
        'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Crispy hollow puris filled with warm spiced ragda/potato mix, served with icy tangy mint-coriander water and sweet tamarind saunth.',
        'availability': 'In Stock',
        'total_reviews': 380,
    },
    {
        'title': 'Bombay Butter Pav Bhaji (2 Pavs)',
        'brand': 'Maaza Chat Bandi',
        'category': 'Chat Bandi',
        'price': 120.00,
        'imageUrl': 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': True,
        'description': 'Mashed spiced mixed vegetables cooked on a flat tawa with a generous slab of butter, served with soft toasted pavs, onions, and lemon.',
        'availability': 'In Stock',
        'total_reviews': 410,
    },
    {
        'title': 'Special Sev Puri Chaat',
        'brand': 'Maaza Chat Bandi',
        'category': 'Chat Bandi',
        'price': 65.00,
        'imageUrl': 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Crispy flat papdis topped with spiced potatoes, chopped onions, raw mango, spicy green chutney, sweet chutney, and a mound of fine sev.',
        'availability': 'In Stock',
        'total_reviews': 220,
    },
    {
        'title': 'Dahi Papdi Chaat Delight',
        'brand': 'Maaza Chat Bandi',
        'category': 'Chat Bandi',
        'price': 80.00,
        'imageUrl': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Crunchy wafers covered with chilled sweetened yogurt, pomegranate seeds, roasted cumin, and dual chutneys.',
        'availability': 'In Stock',
        'total_reviews': 190,
    },
    {
        'title': 'Crispy Samosa Chaat Bowl',
        'brand': 'Maaza Chat Bandi',
        'category': 'Chat Bandi',
        'price': 75.00,
        'imageUrl': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Crushed hot potato samosas layered with spicy chickpea chole curry, onions, curd, and zesty street chaat masalas.',
        'availability': 'In Stock',
        'total_reviews': 260,
    },

    # ------------------ JUICE CENTER ------------------
    {
        'title': 'Fresh Alphonso Mango Shake',
        'brand': 'Maaza Juice Center',
        'category': 'Juice Center',
        'price': 90.00,
        'imageUrl': 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'Made from 100% natural Alphonso mango pulp blended with rich chilled milk and topped with mango chunks and nuts.',
        'availability': 'In Stock',
        'total_reviews': 350,
    },
    {
        'title': 'Fresh Sweet Mosambi Juice',
        'brand': 'Maaza Juice Center',
        'category': 'Juice Center',
        'price': 70.00,
        'imageUrl': 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
        'rating': 4.6,
        'is_prime': False,
        'description': 'Freshly squeezed sweet lime juice served with a pinch of black salt and roasted cumin powder. 100% pure vitamin C.',
        'availability': 'In Stock',
        'total_reviews': 180,
    },
    {
        'title': 'Cold Coffee with Vanilla Scoop',
        'brand': 'Maaza Juice Center',
        'category': 'Juice Center',
        'price': 95.00,
        'imageUrl': 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Creamy blended espresso cold coffee topped with a scoop of rich vanilla ice cream and chocolate drizzle.',
        'availability': 'In Stock',
        'total_reviews': 270,
    },
    {
        'title': 'Chilled Royal Badam Milk',
        'brand': 'Maaza Juice Center',
        'category': 'Juice Center',
        'price': 80.00,
        'imageUrl': 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Slow-simmered almond milk flavored with saffron strands, crushed pistachios, and green cardamom.',
        'availability': 'In Stock',
        'total_reviews': 200,
    },
    {
        'title': 'Sparkling Mint Fresh Lime Soda',
        'brand': 'Maaza Juice Center',
        'category': 'Juice Center',
        'price': 50.00,
        'imageUrl': 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
        'rating': 4.5,
        'is_prime': False,
        'description': 'Refreshing bubbly soda with freshly squeezed lime, crushed garden mint, and your choice of sweet, salt or mixed.',
        'availability': 'In Stock',
        'total_reviews': 160,
    },

    # ------------------ SWEETS / DESSERTS ------------------
    {
        'title': 'Hot Gulab Jamun with Rabdi (2 Pcs)',
        'brand': 'Maaza Mithai',
        'category': 'Sweets / Desserts',
        'price': 90.00,
        'imageUrl': 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'Warm, melt-in-the-mouth mawa dumplings soaked in rose-cardamom sugar syrup, served over chilled thick malai rabdi.',
        'availability': 'In Stock',
        'total_reviews': 430,
    },
    {
        'title': 'Hyderabadi Double Ka Meetha',
        'brand': 'Maaza Mithai',
        'category': 'Sweets / Desserts',
        'price': 110.00,
        'imageUrl': 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
        'rating': 4.9,
        'is_prime': True,
        'description': 'The royal Nizami dessert: golden fried bread crisps soaked in saffron-infused rabdi milk, garnished with cashews, almonds, and silver vark.',
        'availability': 'In Stock',
        'total_reviews': 380,
    },
    {
        'title': 'Royal Kesar Rasmalai (2 Pcs)',
        'brand': 'Maaza Mithai',
        'category': 'Sweets / Desserts',
        'price': 100.00,
        'imageUrl': 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Soft cottage cheese discs steeped in saffron and cardamom flavored condensed milk, served chilled with pistachio slivers.',
        'availability': 'In Stock',
        'total_reviews': 290,
    },
    {
        'title': 'Authentic Qubani Ka Meetha',
        'brand': 'Maaza Mithai',
        'category': 'Sweets / Desserts',
        'price': 120.00,
        'imageUrl': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
        'rating': 4.8,
        'is_prime': False,
        'description': 'Classic Hyderabad dessert made with dried apricots stewed in sweet syrup, topped with apricot kernels and fresh clotted cream.',
        'availability': 'In Stock',
        'total_reviews': 260,
    },
    {
        'title': 'Traditional Malai Matka Kulfi',
        'brand': 'Maaza Mithai',
        'category': 'Sweets / Desserts',
        'price': 75.00,
        'imageUrl': 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
        'rating': 4.7,
        'is_prime': False,
        'description': 'Dense, creamy slow-churned Indian ice cream served in a traditional earthen clay pot with pistachio and rose water aroma.',
        'availability': 'In Stock',
        'total_reviews': 210,
    }
]

created_count = 0
for item in dishes:
    Product.objects.create(
        title=item['title'],
        brand=item['brand'],
        category=item['category'],
        price=item['price'],
        imageUrl=item['imageUrl'],
        rating=item['rating'],
        is_prime=item['is_prime'],
        description=item['description'],
        availability=item['availability'],
        total_reviews=item['total_reviews'],
        seller=seller
    )
    created_count += 1

print(f"Successfully seeded {created_count} delicious dishes for Maaza Cafe!")
print("Categories covered:", set(Product.objects.values_list('category', flat=True)))
print("Prime deals count:", Product.objects.filter(is_prime=True).count())
